elements = [
    "asset://nextBot_sample/funny_nextbot.xml",
]

toybox_items = [
    { category = "Bot", name = "dummy_face", icon = "asset://nextBot_sample/dummy_face.png", description = "dummy_face", element = "dummy_face" },
]
